require('texoport').init {
  { 'tpope/vim-sleuth' },
  require 'plugins.tmux_navigation',
  require 'plugins.cmp',
  require 'plugins.lint',
  require 'plugins.neo_tree',
  require 'plugins.comment',
  require 'plugins.gitsigns',
  require 'plugins.autopairs',
  require 'plugins.surround',
  require 'plugins.spectre',
  require 'plugins.oil',
  require 'plugins.telescope',
  require 'plugins.lspconfig',
  require 'plugins.formatter',
  require 'plugins.solarized',
  require 'plugins.copilot',
  require 'plugins.todo_comments',
  require 'plugins.mini',
  require 'plugins.treesitter',
  require 'plugins.lazygit',
}
